#!/bin/sh

VERSION=0.9
JARFILE=duffel-$VERSION-standalone.jar
URL=https://github.com/mediocregopher/duffel/blob/master/$JARFILE?raw=true
TARGETDIR=~/.duffel

mkdir -p $TARGETDIR
if [ ! -f $TARGETDIR/$JARFILE ]; then
    wget $URL -O $TARGETDIR/$JARFILE
fi

echo "Booting up JVM" >&2

java -jar $TARGETDIR/$JARFILE $@
